#Should /explode cause fire?
explodefire: false
#Should /explode blow up blocks?
explodeblocks: true
#Default power of /explode
explodepower: 4
#Max amount of power until explosionman.explodebig
explodebigpower: 50
#Should /fexplode cause fire?
fexplodefire: false
#Should /fexplode blow up blocks?
fexplodeblocks: true
#Default amount for /fexplode
fexplodepower: 4
#Max amount of power until explosionman.fexplodebig
fexplodebigpower: 50
#Item used for the Boomstick
item: 280
#Should boomstick cause fire?
boomfire: false
#Should boomstick break blocks?
#boomblocks: true
#Power of the Boomstick
boompower: 4
#Power of explosion on death if player has explosionman.deathexplode
deathpower: 4
#Sets if there should be an explode message
explodemsg: False
#What should the explode message be
explodetext: "Insert Message here"
#Sets if there should be an fexplode message
fexplodemsg: False
#What should the fexplode message be
fexplodetext: "Insert Message here"
#Sets if there should be a boomstick message
boomstickmsg: False
#What should the boomstick message be
boomsticktext: "Insert Message here"
#Should /launch cause fire?
launchfire: false
#Should launch break blocks?
launchblocks: true
#What should the power of /launch be
launchpower: 4
#What should the height of the launch be (WARNING: Normal jump of a player is around 0.5)
#MAXIMUM OF 10.0
launchheight: 4
#Should there be a message on launch?
launchmsg: False
#What should the launch message be
launchtxt: "Insert Message here"
#Should /leap cause fire
leapfire: false
#What should the default leap power be (WARNING: jump 3 blocks looking upward with 1)
#MAXIMUM OF 10
leapdefault: 5
#Should there be an explosion at the beginning of a leap 
leapexlpode: True
#Power of leap explosion start
leapstartpower: 4
#Should there be a message on leap
leapmsg: false
#What should the message of the leap be
leaptxt: "Insert message here"
#Should the leapstick cause fire
leapstickfire: false
#Should the leapstick destroy blocks
leapstickblocks: true
#What should the leapstick id be
leapstickid: 289
#Should the leapstick explode on leap
leapstickexlpode: true
#What should the power of the leapstick explode be
leapstickstartpower: 4
#Should theere be a leapstick message 
leapstickmsg: false
#What should the message of the leapstick be
leapsticktxt: "Insert Message here"
testms:

