name: Explosion Man
main: com.gmail.bunnehrealm.explosionman.MainClass
version: 1.8
description: >
            Explosion Man Commands!
commands:
  explode:
    description: Creates an Explosion! Usage - /explode [Power]
  fexplode:
    description: Creates an Explosion where you are looking! Usage - /fexplode [power]
  launch:
    description: Creates an explosion and shoots you in the air! Usage - /launch [power]
  leap:
    description: Makes you leap like a bunny
  explodekit:
    description: Gives the command user the explode kit
  setboomstick:
    description: Sets the item id of the boomstick!
  setleapstick:
    description: Sets the item id of the leapstick!
  myboom:
    description: Allows player to set their own boomstick!